tags = [
  [
    "Axel",
    tagEntries = [
        "90prozent",
        "bertruhe",
        "derelektrojude",
        "ichbegrueszesie",
        "imp",
        "implosionstechnologie",
        "kleinarbeit",
        "logarithmischespirale",
        "magie",
        "microwellenstrahler",
        "physik",
        "raumfahrt",
        "silencium",
        "sonne",
        "strafplanet",
        "transmedialekontakte",
        "wetterkrieg",
        "wissen",
        "wissenschaften",
        "wissenumdiewahrephysik"
    ]
  ],
  [
    "Simpsons",
    tagEntries = [
        "bbbbbb",
        "carleave",
        "excludi1",
        "excludi2",
        "excludi3",
        "flanders",
        "kaufmich",
        "mahok2",
        "monarchenschweine",
        "planeleave",
        "sabbat",
        "schinkengeklaut",
        "scots",
        "sogutwietot",
        "spinnengift",
        "streikbrecher",
        "wurm",
        "zink",
        "zwiebel"
    ]
  ],
  [
    "Bully",
    tagEntries = [
        "deckungdeswaldes",
        "deinname",
        "majestet",
        "miristfad",
        "oesterreich",
        "oesterreich2",
        "unsistsofad"
    ]
  ],
  [
    "Batman",
    tagEntries = [
        "batfranzosisch",
        "batgurt",
        "epigram",
        "hurr",
        "kamelgras",
        "praxis",
        "zwangslage",
        "zynisch"
    ]
  ],
  [
    "VFX",
    tagEntries = [
        "ak47",
        "brokeit",
        "dasvolk",
        "dasvolk2",
        "dasvolk3",
        "diablo",
        "fussspuren",
        "hunger",
        "jawohl",
        "monsterkill",
        "ps1",
        "sodom",
        "steelrain",
        "superhot",
        "supremenavalinvade",
        "zelda",
        "zahlen"
    ]
  ],
  [
    "Werner",
    tagEntries = [
        "einwas",
        "jameister",
        "keinerussen",
        "rohrich",
        "russenda",
        "snuffelstuck"
    ]
  ],
  [
    "Filme",
    tagEntries = [
        "airwolf",
        "alteleier",
        "bekehrten",
        "dasandere",
        "energiekrise",
        "franzosisch",
        "gebusch",
        "guteidee",
        "kohlen",
        "kohlen2",
        "kohlen3",
        "konig",
        "kreuzwortbanane",
        "maechtiger",
        "nett",
        "senat",
        "verbrennen",
        "wasserpfeife"
    ]
  ],
  [
    "Songs",
    tagEntries = [
        "arky",
        "arky2",
        "arky3",
        "arky4",
        "bellmarch",
        "convoy",
        "convoy2",
        "convoy3",
        "dasandere",
        "oz",
        "praise",
        "praiselong",
        "riseandshine",
        "segata",
        "segata2",
        "segata3",
        "speedra",
        "titanic",
        "unserlied"
    ]
  ],
  [
    "Spongebob",
    tagEntries = [
        "geistigemechanismen",
        "hinterdiefelsen",
        "wambo1",
        "wambo2",
        "weewoo",
        "west",
        "westfired"
    ]
  ],
  [
    "Nonsense",
    tagEntries = [
        "beenasfar",
        "beenasfar2"
    ]
  ],
];