tags = [
  [
    "Axel",
    [
      "90prozent",
      "bertruhe",
      "derelektrojude",
      "ichbegrueszesie",
      "imp",
      "implosionstechnologie",
      "kleinarbeit",
      "logarithmischespirale",
      "magie",
      "microwellenstrahler",
      "physik",
      "raumfahrt",
      "silencium",
      "sonne",
      "strafplanet",
      "transmedialekontakte",
      "wetterkrieg",
      "wissen",
      "wissenschaften",
      "wissenumdiewahrephysik"
    ]
  ],
  [
    "Simpsons",
    [
      "bbbbbb",
      "bier",
      "carleave",
      "esel",
      "flanders",
      "kaufmich",
      "mahok2",
      "monarchenschweine",
      "paddlin",
      "planeleave",
      "sabbat",
      "schinkengeklaut",
      "scots",
      "sogutwietot",
      "spinnengift",
      "streikbrecher",
      "uter",
      "uter2",
      "wurm",
      "yoink",
      "zink",
      "zufett",
      "zwiebel"
    ]
  ],
  [
    "Bully",
    [
      "deckungdeswaldes",
      "deinname",
      "majestet",
      "miristfad",
      "oesterreich",
      "oesterreich2",
      "unsistsofad"
    ]
  ],
  [
    "Batman",
    [
      "batfranzosisch",
      "batgurt",
      "epigram",
      "hurr",
      "kamelgras",
      "praxis",
      "zwangslage",
      "zynisch"
    ]
  ],
  [
    "VFX",
    [
      "ak47",
      "brokeit",
      "dasvolk",
      "dasvolk2",
      "dasvolk3",
      "diablo",
      "fussspuren",
      "hunger",
      "jawohl",
      "monsterkill",
      "ps1",
      "sodom",
      "steelrain",
      "superhot",
      "supremenavalinvade",
      "tumbleweed",
      "zahlen",
      "zelda"
    ]
  ],
  [
    "Werner",
    [
      "einwas",
      "jameister",
      "keinerussen",
      "rohrich",
      "russenda",
      "snuffelstuck"
    ]
  ],
  [
    "Filme",
    [
      "airwolf",
      "alteleier",
      "bekehrten",
      "buchderfriesen",
      "dasandere",
      "energiekrise",
      "franzosisch",
      "gebusch",
      "guteidee",
      "kohlen",
      "kohlen2",
      "kohlen3",
      "konig",
      "kreuzwortbanane",
      "maechtiger",
      "nett",
      "senat",
      "verbrennen",
      "wasserpfeife",
      "wrong",
      "zink"
    ]
  ],
  [
    "Songs",
    [
      "arky",
      "arky2",
      "arky3",
      "arky4",
      "bellmarch",
      "convoy",
      "convoy2",
      "convoy3",
      "dasandere",
      "oz",
      "praise",
      "praiselong",
      "riseandshine",
      "segata",
      "segata2",
      "segata3",
      "speedra",
      "titanic",
      "unserlied"
    ]
  ],
  [
    "Spongebob",
    [
      "geistigemechanismen",
      "hinterdiefelsen",
      "wambo1",
      "wambo2",
      "weewoo",
      "west",
      "westfired"
    ]
  ],
  [
    "Nonsense",
    [
      "beenasfar",
      "beenasfar2"
    ]
  ],
  [
    "Zugzeit",
    [
      "zuege",
      "zugbremse",
      "zugdauerundrichtung",
      "zugistkrass",
      "zugzeit",
      "zugzeit2",
      "zugzeit3",
      "zugzeit4",
      "zugzeitherzlichwillkomen"
    ]
  ],
  [
    "Spencer&Hill",
    [
      "gott",
      "vogt",
      "wildsau"
    ]
  ]
]